[theme]
primaryColor="#FF4B4B"      # Streamlit Red
backgroundColor="#F0F2F6"   # Light gray
secondaryBackgroundColor="#FFFFFF" # White for elements
textColor="#262730"        # Dark gray text
font="sans serif"